# ╭─────────────── ✦ ────────────────╮
#│           INITIALIZE APPS           │
# ╰─────────────── ✦ ────────────────╯


exec-once = quickshell &
exec-once = sh -c 'wl-paste --watch cliphist store' &
exec-once = swww-daemon &
exec-once = nm-applet &




# ╭─────────────── ✦ ────────────────╮
#│      HYPRLAND CONFIGURATION       │
# ╰─────────────── ✦ ────────────────╯
#
# Author    : archayu
# GitHub    : https://github.com/archayu/dotfiles
# Config    : Hyprland dynamic tiling compositor
