
# -------------------
# Source other config files
# -------------------
source = $HOME/.config/hypr/keybinds.conf
source = $HOME/.config/hypr/autostart.conf
source  = $HOME/.config/hypr/Palette/mocha.conf
source = $HOME/.config/hypr/windowrules.conf
source = $HOME/.config/hypr/decoration.conf

# -------------------
# Monitor configuration
# -------------------
monitor=eDP-1,1920x1080@60,0x0,1.20


# -------------------
# Input configuration
# -------------------
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
    }
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

# -------------------
# Environment variables
# -------------------
env = XCURSOR_THEME,catppuccin-mocha-red-cursors
env = XCURSOR_SIZE,24   # or your preferred size







# ╭─────────────── ✦ ────────────────╮
#│      HYPRLAND CONFIGURATION       │
# ╰─────────────── ✦ ────────────────╯
#
# Author    : archayu
# GitHub    : https://github.com/archayu/dotfiles
# Config    : Hyprland dynamic tiling compositor